default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false
  username: root
  password: filip08
  pool: 50
  host: 127.0.0.1

development:
  <<: *default
  database: band_notifier


production:
  adapter: mysql2
  host: zdenac.eu
  database: band_notifier
  username: root
  password: studio89
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
